# Generated by Django 5.0.3 on 2024-03-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshortener',
            old_name='short_url',
            new_name='shortened_url',
        ),
    ]
